name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Hoặc phiên bản Node.js bạn muốn

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        # Chạy script build từ package.json gốc
        run: npm run build

      - name: Deploy Project Artifacts to Vercel
        # Deploy thư mục gốc, Vercel sẽ đọc cấu hình từ file .vercel/project.json
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}